#!/usr/bin/env python3
"""
Build script to combine all topic files back into a single data.js
Run this when you make changes to any topic file.
"""

import os

SCRIPT_ORDER = [
    # DSA Topics
    'data/dsa/arrays.js',
    'data/dsa/binary_search.js',
    'data/dsa/linked_list.js',
    'data/dsa/stack.js',
    'data/dsa/trees.js',
    'data/dsa/graphs.js',
    'data/dsa/dp.js',
    'data/dsa/heap_trie.js',
    'data/dsa/backtracking.js',
    # Concepts
    'data/concepts/dp_concepts.js',
    'data/concepts/arrays_concepts.js',
    'data/concepts/graphs_concepts.js',
    'data/concepts/trees_concepts.js',
    'data/concepts/complexity_concepts.js',
    # Combiner
    'data/index.js',
]


def build():
    output_lines = [
        '// Auto-generated from data/ folder',
        '// Run `python3 build_data.py` to regenerate',
        '// DO NOT EDIT THIS FILE DIRECTLY - Edit files in data/ folder instead!',
        '',
    ]
    
    for script_path in SCRIPT_ORDER:
        if not os.path.exists(script_path):
            print(f'Warning: {script_path} not found!')
            continue
        
        with open(script_path, 'r') as f:
            content = f.read()
        
        # Add separator comment
        output_lines.append(f'\n// ========== {script_path} ==========')
        output_lines.append(content)
    
    # Write the combined file
    with open('data.js', 'w') as f:
        f.write('\n'.join(output_lines))
    
    print('Built data.js successfully!')
    print(f'Combined {len(SCRIPT_ORDER)} files.')

if __name__ == '__main__':
    build()
